### ISSUE TITLE
helm chart does not allow for a different namespace

### ISSUE THREAD

**Issue by draganm** [DopplerHQ/helm-charts#12]
Current chart is just a single YAML without any variables.
It forces creation of `doppler-operator-system`, which is not the default behaviour of most other helm charts from other projects.

**Comment by nmanoogian** [comment]
Hi @draganm, thanks for calling this out 👍 

To confirm, you would have expected the operator namespace to be configurable as a variable in the chart?

**Comment by draganm** [comment]
yes, and also this not to be part of the chart (currently in `templates/all.yaml`):
```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: doppler-operator-system
```

it's wrong on many levels ... 
- helm will create a namespace for you if you pass the `--create-namespace` parameter
- it completely ignores the namespace parameter that helm will pass
- it makes `hashicorp/helm` terraform provider fail when `namespace` parameter is passed, even if the value is `doppler-operator-system`
